/* src/af_auto.h.  Generated by configure.  */
#define SIZEOF_INT 4
#define SIZEOF_LONG_INT 4
#define SIZEOF_SHORT_INT 2
#define HAVE_XERCESC_UTIL_XERCESVERSION_HPP 1
#define HAVE_LIBXERCES_C 1
#include "version.h"
